// GENERATED by scripts/generate-river-mask.mjs — do not edit by hand.
//
// The Summoner's Rift river, read off the game's own minimap artwork
// (assets/minimap-blank-sr.png) rather than estimated from coordinates.
// Re-run the generator if the artwork is ever updated; it prints the extracted
// shape so the result can be eyeballed before committing.
//
// Stored as a 64x64 bitmask in row-major *screen* order — row 0 is the
// north edge — which is why the lookup flips Y: game coordinates put the
// origin at the bottom-left.

import { Position, MapType, MAP_DIMENSIONS } from '../core/types';

const GRID = 64;
const MASK = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwBAAAAAAAADgAQAAAAAAAOADAAAAAAAAwAMAAAAAAADAAwAAAAAAAIDjAAAAAACAgOcBAAAAAAAA/wEAAAAAAAD/AAAAAAAAAP4AAAAAAAAA/AAAAAAAAAD4BwAAAAAAAPAPAAAAAAAAwB8AAAAAAAAAPwAAAAAAAAB4AAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAY8AAAAAAAABvwAAAAAAAAG+AMAAAAAAADwHwAAAAAAAMA/AAAAAAAAAH4AAAAAAAAA/gAAAAAAAAD+AQAAAAAAAP4DAAAAAAAA3gMAAAAAAACOAwAAAAAAAIAHAAAAAAAAgAcAAAAAAACADwAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

// Decoded by hand rather than via atob() or Buffer: this module is imported
// by both the WebView bundle and the node-based test runner, and neither of
// those globals exists in both.
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const bits = (() => {
  const clean = MASK.replace(/=+$/, '');
  const out = new Uint8Array(Math.floor(clean.length * 3 / 4));
  let acc = 0, accBits = 0, o = 0;
  for (let i = 0; i < clean.length; i++) {
    acc = (acc << 6) | B64.indexOf(clean[i]);
    accBits += 6;
    if (accBits >= 8) {
      accBits -= 8;
      out[o++] = (acc >> accBits) & 0xff;
    }
  }
  return out;
})();

/**
 * Is this position standing in the river?
 *
 * Howling Abyss has no river — it is one bridge over a chasm — so it always
 * answers false rather than borrowing Summoner's Rift's geometry.
 */
export function isInRiver(pos: Position | null | undefined, mapType: MapType): boolean {
  if (!pos || mapType !== 'summoners_rift') return false;
  const dims = MAP_DIMENSIONS.summoners_rift;
  const u = pos.x / dims.width;
  const v = 1 - pos.y / dims.height;
  if (u < 0 || u >= 1 || v < 0 || v >= 1) return false;
  const gx = Math.min(GRID - 1, Math.floor(u * GRID));
  const gy = Math.min(GRID - 1, Math.floor(v * GRID));
  const i = gy * GRID + gx;
  return (bits[i >> 3] & (1 << (i & 7))) !== 0;
}
